@startuml PeerPack_Database_Schema

entity users {
  full_name : varchar
  rating : decimal
}

entity trips {
  ● user_id : bigint
  origin : varchar
  destination : varchar
  depart_at : timestamp
  capacity_kg : int
}

entity parcels {
  ● user_id : bigint
  title : varchar
  weight_kg : decimal
  reward : decimal
  status : open | assigned | delivered
}

entity offers {
  ● trip_id : bigint
  ● parcel_id : bigint
  type : parcel_to_trip | trip_to_parcel
  price : decimal
  status : pending | rejected | accepted
}

entity deliveries {
  ● parcel_id : bigint
  ● trip_id : bigint
  ● carrier_user_id : bigint
  status : assigned | in_transit | delivered
}

' ========== СВЯЗИ ==========
users ||--o{ trips
users ||--o{ parcels
users ||--o{ offers
users ||--o{ deliveries

trips ||--o{ offers
parcels ||--o{ offers

trips ||--o{ deliveries
parcels ||--|| deliveries

@enduml